/* ========================
   data.js - App Data Store
   ======================== */

const NSC_DATA = {

  nowShowing: [
    {
      id: 1,
      title: "Pengabdi Setan 3",
      year: 2025,
      genre: ["Horor", "Thriller"],
      duration: 118,
      rating: 8.2,
      ageRating: "17+",
      badge: "HOT",
      emoji: "👁️",
      color: "#1a0a0a",
      director: "Joko Anwar",
      cast: "Tara Basro, Endy Arfian, Nasar Annuz",
      synopsis: "Rumah di atas bukit itu kembali menyimpan teror. Setelah tragedi yang menghantui keluarga Mawarni, kini bahaya datang dari dalam darah mereka sendiri. Sebuah kutukan yang tak pernah benar-benar pergi.",
    },
    {
      id: 2,
      title: "Dune: Part Three",
      year: 2025,
      genre: ["Sci-Fi", "Aksi"],
      duration: 175,
      rating: 9.0,
      ageRating: "13+",
      badge: "IMAX",
      emoji: "🏜️",
      color: "#1a1200",
      director: "Denis Villeneuve",
      cast: "Timothée Chalamet, Zendaya, Austin Butler",
      synopsis: "Paul Atreides memimpin pemberontakan terakhir melawan Kaisar Galaktik. Takdir semesta bergantung pada keputusan seorang manusia yang kini menjadi lebih dari manusia.",
    },
    {
      id: 3,
      title: "Antologi Nusantara",
      year: 2025,
      genre: ["Drama", "Budaya"],
      duration: 130,
      rating: 8.7,
      ageRating: "Semua Umur",
      badge: "PILIHAN",
      emoji: "🏝️",
      color: "#001a0a",
      director: "Riri Riza, Mouly Surya",
      cast: "Nicholas Saputra, Raisa Andriana, Reza Rahadian",
      synopsis: "Lima cerita dari lima pulau Indonesia. Satu bangsa dengan seribu wajah, seribu rasa, dan satu jiwa yang sama. Sebuah perayaan keberagaman di layar lebar.",
    },
    {
      id: 4,
      title: "The Last Archipelago",
      year: 2025,
      genre: ["Petualangan", "Aksi"],
      duration: 142,
      rating: 7.9,
      ageRating: "13+",
      badge: "4DX",
      emoji: "⚡",
      color: "#0a0a1a",
      director: "Angga Dwimas Sasongko",
      cast: "Joe Taslim, Chelsea Islan, Iko Uwais",
      synopsis: "Di lautan yang belum terpetakan, seorang pelaut menemukan ancaman yang mengancam seluruh kepulauan Nusantara. Petualangan seru yang mendebarkan dari ujung ke ujung.",
    },
    {
      id: 5,
      title: "Laskar Pelangi 2",
      year: 2025,
      genre: ["Drama", "Inspirasi"],
      duration: 125,
      rating: 8.5,
      ageRating: "Semua Umur",
      badge: "UNGGULAN",
      emoji: "🌈",
      color: "#1a1000",
      director: "Riri Riza",
      cast: "Cut Mini, Ikranagara, generasi baru Laskar",
      synopsis: "Dua puluh tahun kemudian, anak-anak Belitung bertemu kembali. Mimpi mereka ada yang terwujud, ada yang terluka—namun semangat mereka tidak pernah padam.",
    },
  ],

  comingSoon: [
    {
      id: 101,
      title: "Avengers: Final War",
      releaseDate: "15 Agustus 2025",
      genre: ["Superhero", "Aksi"],
      emoji: "⚡",
      color: "#0d0015",
      badge: "SEGERA",
    },
    {
      id: 102,
      title: "Superhero Indonesia",
      releaseDate: "23 Agustus 2025",
      genre: ["Aksi", "Fantasi"],
      emoji: "🦅",
      color: "#00100a",
      badge: "SEGERA",
    },
    {
      id: 103,
      title: "Perahu Kertas 3",
      releaseDate: "5 September 2025",
      genre: ["Romansa", "Drama"],
      emoji: "🌊",
      color: "#00101a",
      badge: "SEGERA",
    },
    {
      id: 104,
      title: "Ghost Protocol: Jakarta",
      releaseDate: "18 September 2025",
      genre: ["Thriller", "Aksi"],
      emoji: "🌆",
      color: "#0a0a0a",
      badge: "SEGERA",
    },
  ],

  promos: [
    {
      id: 1,
      title: "Selasa Hemat",
      emoji: "🎟️",
      discount: "50%",
      desc: "Setiap hari Selasa, semua tiket reguler diskon 50% untuk pemegang NSC Card.",
      terms: "Berlaku untuk studio reguler, maks. 2 tiket. Tidak berlaku untuk studio premium.",
      badge: "NSC Card",
    },
    {
      id: 2,
      title: "Student Pass",
      emoji: "🎓",
      discount: "30%",
      desc: "Diskon eksklusif mahasiswa aktif dengan menunjukkan KTM yang berlaku.",
      terms: "Berlaku setiap hari untuk semua jenis studio, tidak berlaku weekend.",
      badge: "Pelajar",
    },
    {
      id: 3,
      title: "Family Package",
      emoji: "👨‍👩‍👧‍👦",
      discount: "4+1",
      desc: "Beli 4 tiket, dapatkan 1 tiket gratis untuk nonton bareng keluarga.",
      terms: "Berlaku untuk studio reguler dan Gold Class. Tiket gratis senilai yang terendah.",
      badge: "Keluarga",
    },
    {
      id: 4,
      title: "BCA Privilege",
      emoji: "💳",
      discount: "25%",
      desc: "Diskon spesial kartu kredit BCA Mastercard dan Visa untuk nonton di NSC.",
      terms: "Berlaku untuk semua studio. Maks. diskon Rp50.000 per transaksi.",
      badge: "BCA",
    },
    {
      id: 5,
      title: "Birthday Treat",
      emoji: "🎂",
      discount: "1 Gratis",
      desc: "Nonton gratis di hari ulang tahun Anda! Tunjukkan KTP dan NSC Card.",
      terms: "Berlaku di hari ulang tahun saja, untuk studio reguler. 1 tiket per orang.",
      badge: "Ulang Tahun",
    },
    {
      id: 6,
      title: "OVO & GoPay",
      emoji: "📱",
      discount: "20%",
      desc: "Bayar dengan OVO atau GoPay dan nikmati cashback untuk pembelian tiket online.",
      terms: "Cashback maks. Rp30.000. Berlaku setiap hari untuk semua studio.",
      badge: "Digital",
    },
  ],

  cinemas: [
    { id: 1, name: "NSC Grand Jakarta", city: "Jakarta", area: "Jawa", address: "Mall Grand Indonesia, Jakarta Pusat", features: ["IMAX", "4DX", "Gold Class", "Screen X"], studios: 14, emoji: "🏙️" },
    { id: 2, name: "NSC Pondok Indah", city: "Jakarta", area: "Jawa", address: "Pondok Indah Mall 3, Jakarta Selatan", features: ["IMAX", "Gold Class", "Dolby Atmos"], studios: 10, emoji: "🌟" },
    { id: 3, name: "NSC Kelapa Gading", city: "Jakarta", area: "Jawa", address: "Mall Kelapa Gading 5, Jakarta Utara", features: ["4DX", "Dolby Atmos"], studios: 8, emoji: "🎬" },
    { id: 4, name: "NSC Ciputra Surabaya", city: "Surabaya", area: "Jawa", address: "Ciputra World Surabaya, Jl. Mayjend Sungkono", features: ["IMAX", "4DX", "Gold Class"], studios: 12, emoji: "🦅" },
    { id: 5, name: "NSC Tunjungan Plaza", city: "Surabaya", area: "Jawa", address: "Tunjungan Plaza 6, Surabaya", features: ["Dolby Atmos", "Screen X"], studios: 8, emoji: "🎭" },
    { id: 6, name: "NSC Paris Van Java", city: "Bandung", area: "Jawa", address: "Paris Van Java Mall, Jl. Sukajadi Bandung", features: ["IMAX", "4DX"], studios: 10, emoji: "🌸" },
    { id: 7, name: "NSC Trans Studio Bandung", city: "Bandung", area: "Jawa", address: "Trans Studio Mall, Jl. Gatot Subroto", features: ["Gold Class", "Dolby Atmos"], studios: 8, emoji: "🎪" },
    { id: 8, name: "NSC Hartono Yogyakarta", city: "Yogyakarta", area: "Jawa", address: "Hartono Mall, Jl. Ring Road Utara Yogyakarta", features: ["4DX", "Dolby Atmos"], studios: 7, emoji: "🏛️" },
    { id: 9, name: "NSC Plaza Medan Fair", city: "Medan", area: "Sumatra", address: "Plaza Medan Fair, Jl. Gatot Subroto Medan", features: ["IMAX", "Gold Class"], studios: 10, emoji: "🌴" },
    { id: 10, name: "NSC Sun Plaza Medan", city: "Medan", area: "Sumatra", address: "Sun Plaza, Jl. KH Zainul Arifin Medan", features: ["4DX", "Dolby Atmos"], studios: 8, emoji: "☀️" },
    { id: 11, name: "NSC Palembang Icon", city: "Palembang", area: "Sumatra", address: "Palembang Icon, Jl. POM IX Palembang", features: ["IMAX", "4DX"], studios: 9, emoji: "🌉" },
    { id: 12, name: "NSC SKA Pekanbaru", city: "Pekanbaru", area: "Sumatra", address: "SKA Mall, Jl. Soekarno Hatta Pekanbaru", features: ["Dolby Atmos"], studios: 6, emoji: "🌿" },
    { id: 13, name: "NSC Trans Studio Makassar", city: "Makassar", area: "Sulawesi", address: "Trans Studio Mall Makassar, Jl. Metro Tanjung Bunga", features: ["IMAX", "Gold Class", "4DX"], studios: 11, emoji: "⚓" },
    { id: 14, name: "NSC Balikpapan Super Block", city: "Balikpapan", area: "Kalimantan", address: "Balikpapan Super Block, Jl. Jend. Sudirman", features: ["Dolby Atmos", "4DX"], studios: 7, emoji: "💎" },
    { id: 15, name: "NSC Discovery Bali", city: "Denpasar", area: "Bali & Timur", address: "Discovery Shopping Mall, Jl. Kartika Plaza Kuta", features: ["IMAX", "Gold Class"], studios: 8, emoji: "🌺" },
    { id: 16, name: "NSC Jayapura", city: "Jayapura", area: "Bali & Timur", address: "Ramayana Mall, Jl. Percetakan Jayapura", features: ["Dolby Atmos"], studios: 5, emoji: "🦜" },
  ],

  teamMembers: [
    { name: "toreto", role: "CEO & Founder (kadang pembalap)", emoji: "👨‍💼" },
    { name: "mia", role: "COO", emoji: "👩‍💼" },
    { name: "brian", role: "Chief Content Officer", emoji: "🎬" },
    { name: "roman", role: "Chief Marketing Officer", emoji: "📣" },
  ],

  milestones: [
    { year: "2005", event: "New Star Cineplex berdiri di Jakarta dengan 1 gedung pertama" },
    { year: "2008", event: "Ekspansi ke Surabaya dan Bandung. Total 5 cabang." },
    { year: "2012", event: "Pertama di Indonesia menghadirkan teknologi IMAX." },
    { year: "2015", event: "Peluncuran NSC Gold Class — pengalaman sinema mewah pertama di Asia Tenggara." },
    { year: "2018", event: "Melewati 1 juta penonton per tahun. 15 cabang aktif." },
    { year: "2021", event: "Teknologi 4DX hadir di Indonesia melalui NSC Grand Jakarta." },
    { year: "2023", event: "NSC Card diluncurkan dengan lebih dari 500.000 anggota aktif." },
    { year: "2025", event: "38 cabang aktif dari Aceh hingga Papua. Terbesar di Indonesia." },
  ],

  scheduleData: {
    dates: [
      { day: "Sen", num: 14 },
      { day: "Sel", num: 15 },
      { day: "Rab", num: 16 },
      { day: "Kam", num: 17 },
      { day: "Jum", num: 18 },
      { day: "Sab", num: 19 },
      { day: "Min", num: 20 },
    ],
    showtimes: [
      {
        filmId: 1,
        film: "Pengabdi Setan 3",
        slots: [
          { time: "10:30", type: "Regular", available: true },
          { time: "13:00", type: "Regular", available: true },
          { time: "15:30", type: "Dolby Atmos", available: true },
          { time: "18:00", type: "Regular", available: false },
          { time: "20:30", type: "IMAX", available: true },
          { time: "23:00", type: "Regular", available: true },
        ]
      },
      {
        filmId: 2,
        film: "Dune: Part Three",
        slots: [
          { time: "11:00", type: "Regular", available: true },
          { time: "14:00", type: "IMAX", available: true },
          { time: "17:30", type: "Dolby Atmos", available: false },
          { time: "21:00", type: "IMAX", available: true },
        ]
      },
      {
        filmId: 3,
        film: "Antologi Nusantara",
        slots: [
          { time: "12:00", type: "Regular", available: true },
          { time: "14:30", type: "Regular", available: true },
          { time: "17:00", type: "Gold Class", available: true },
          { time: "19:30", type: "Regular", available: true },
        ]
      },
    ]
  }
};
